2021-09-27 20:53:21,245 ERROR: Exception on /reset_password_request [POST] [in E:\Repos\personal\Flask Mega Tutorial\venv\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "E:\Repos\personal\Flask Mega Tutorial\venv\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\Repos\personal\Flask Mega Tutorial\venv\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\Repos\personal\Flask Mega Tutorial\venv\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\Repos\personal\Flask Mega Tutorial\venv\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "E:\Repos\personal\Flask Mega Tutorial\microblog\app\routes.py", line 160, in reset_password_request
    send_password_reset_email(user)
  File "E:\Repos\personal\Flask Mega Tutorial\microblog\app\email.py", line 12, in send_password_reset_email
    token = user.get_reset_password_token()
  File "E:\Repos\personal\Flask Mega Tutorial\microblog\app\models.py", line 55, in get_reset_password_token
    return jwt.encode({'reset_password': self.id, 'exp': time() + expires_in},
AttributeError: 'str' object has no attribute 'decode'
2021-09-27 20:53:27,294 ERROR: Exception on /reset_password_request [POST] [in E:\Repos\personal\Flask Mega Tutorial\venv\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "E:\Repos\personal\Flask Mega Tutorial\venv\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\Repos\personal\Flask Mega Tutorial\venv\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\Repos\personal\Flask Mega Tutorial\venv\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\Repos\personal\Flask Mega Tutorial\venv\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "E:\Repos\personal\Flask Mega Tutorial\microblog\app\routes.py", line 160, in reset_password_request
    send_password_reset_email(user)
  File "E:\Repos\personal\Flask Mega Tutorial\microblog\app\email.py", line 12, in send_password_reset_email
    token = user.get_reset_password_token()
  File "E:\Repos\personal\Flask Mega Tutorial\microblog\app\models.py", line 55, in get_reset_password_token
    return jwt.encode({'reset_password': self.id, 'exp': time() + expires_in},
AttributeError: 'str' object has no attribute 'decode'
2021-09-27 20:53:56,964 INFO: Microblog startup [in E:\Repos\personal\Flask Mega Tutorial\microblog\app\__init__.py:41]
